### ISSUE TITLE
Can't pass in a unicode string as a key in Python 2

### ISSUE THREAD

**Issue by rtpg** [bdauvergne/python-oath#24]
There's a check on the key in the lastest version of `oath` that checks : `instanceof(key, str)`. This is `False` for instances of `unicode` in Python 2.

I think a reasonable solution would be to attempt conversion to `ascii` if it's a unicode instance, ignoring other characters.

**Comment by bdauvergne** [comment]
I do not see the problem:

    >>> oath.hotp(u'aa', 2)
'    985320'

Could you provide a failing test case ?

**Comment by rtpg** [comment]
Sorry for the kind of sparse report earlier, here's what happens for me (Py2.7, oath==1.4.0):
```
from oath import accept_totp
accept_totp('3133327375706e65726473',u'4e4ba93d', format='hex', period=1800)
-->
[..snip..]
/Users/rtpg/proj/env/lib/python2.7/site-packages/oath/_utils.pyc in compare_digest(a, b)
     30 def compare_digest(a, b):
     31     if not isinstance(a, str) or not isinstance(b, str):
---> 32         raise TypeError
     33     if len(a) != len(b):
     34         return False

**Comment by rtpg** [comment]
So I believe it is the comparison function that is not coercing these values
