### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by foxx** [bdauvergne/python-oath#26]
Do you know of any problems, bugs or features outstanding on this project?

I'm looking to use `python-oath`, but curious to know if there is anything that could potentially cause problems further down the line. The code looks decent, but saw there was a high number of forks and low number of stars, so figured it's better to ask.

Also, thank you for sharing this code, you've saved me many weeks of frustrating work.

**Comment by bdauvergne** [comment]
Maintainer here. There is only 4 forks with commits and most of them are for packaging, I don't know why they do not ask for pull request, I would be happy to integrate the Debian packaging from Q-Leap-Networks. The main repository is mine and I actively maintain it, it's the only one pypi too. It's the first result when you type OATH on Pypi too.

**Comment by foxx** [comment]
Beautiful, thank you for the quick response!
