### ISSUE TITLE
ValueError: non-hexadecimal number found in fromhex() arg at position 0

### ISSUE THREAD

**Issue by foxx** [bdauvergne/python-oath#27]
If a non hex value is given to `accept_totp`, it results in the following exception;

```
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/oath/_totp.py", line 129, in accept_totp
    if _utils.compare_digest(totp(key, format=format, period=period, hash=hash, t=t+d), response):
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/oath/_totp.py", line 61, in totp
    return hotp(key, T, format=format, hash=hash)
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/oath/_hotp.py", line 72, in hotp
    bin_hotp = __hotp(key, counter, hash)
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/oath/_hotp.py", line 39, in __hotp
    bin_key = _utils.fromhex(key)
  File "/home/vagrant/.virtualenvs/vagrant/lib/python3.4/site-packages/oath/_utils.py", line 11, in fromhex
    return bytes.fromhex(s)
```

Should this perhaps check for invalid values, and return `(False, None)` instead, rather than having to catch `ValueError`, which could potentially hide other bugs being raised which are unrelated to invalid user input?

**Comment by bdauvergne** [comment]
I prefer exceptions for error checking, but maybe we could do the check earlier and return a more intelligible ValueError. But in the end the check should be done also by the caller, as python-oath is not a user interface.

Possible patch:

```
diff --git a/oath/_hotp.py b/oath/_hotp.py
index 9944180..22d794e 100644
--- a/oath/_hotp.py
+++ b/oath/_hotp.py
@@ -69,6 +69,14 @@ def hotp(key,counter,format='dec6',hash=hashlib.sha1):
         >>> hotp('343434', 2, format='dec6')
             '791903'
     '''
+    # check key is an hexadecimal string
+    try:
+        key = str(key)
+    except UnicodeEncodeError:
+        raise ValueError('key is not a string')
+    if key.lower().strip('0123456789abcdef'):
+        raise ValueError('key is not an hexadecimal string')
+
     bin_hotp = __hotp(key, counter, hash)
 
     if format == 'dec4':

```

**Comment by foxx** [comment]
Explicitly casting as a string could cause unexpected behaviour for Python 3 users if they pass in bytes, as this would result in `str("b'value'")`. If this approach was used, it would likely need an `isinstance` check to deal with `bytes`. At the same time, you're quite right that `python-oath` is not a user interface and passing the wrong value type is part and parcel of a dynamically typed language. Admittedly the error is not immediately clear, but it's explained in the doc strings. 

I'm thinking a better approach would be to use `ignore_errors=True`, as seen in many python builtins, thoughts?

**Comment by bdauvergne** [comment]
I preferred not to go on the isinstance road as it would need me to finally import 'six' to support python 2&3 with an isinstance(key, six.string_types) and I would prefer not to add a dependency just for that.
I prefer to document that the key must an hexadecimal string-like thing i.e. something which can convert to string and gives a serie of hexadecimal characters.

Anyway if it pass a byte it will generate the string you give which will not pass the hexadecimal check, so anyway you get an expectable ValueError. I don't like ignore_errors=True as I want caller to manage them :) If they want the ignore_errors behaviour they can wrap the call with try/catch Exception: if they want.

**Comment by foxx** [comment]
Makes sense, closing out
