### ISSUE TITLE
Docs sync

### ISSUE THREAD

**Issue by kousu** [bdauvergne/python-oath#28]
https://github.com/bdauvergne/python-oath/blob/172852cb9f245875686c4d5e525a304315b93c4b/oath/_hotp.py#L53 and https://github.com/bdauvergne/python-oath/blob/172852cb9f245875686c4d5e525a304315b93c4b/oath/_totp.py#L32 disagree about legal formats. 'hex40' is not allowed.

**Comment by bdauvergne** [comment]
I think I fixed it, can you confirm ?

**Comment by kousu** [comment]
They match now, but your code also has a 'dec' option that's not listed, too. :)

Why did you rename 'hex40' to 'hex-notrunc'? 'hex40' matches the 'dec<N>' pattern, and I find it more readable.

**Comment by bdauvergne** [comment]
Sorry I really don't remember :) Feel free to provide a PR for dec or restore the possibility of hex40.

**Comment by bdauvergne** [comment]
Now news good news.
