### ISSUE TITLE
Escape warning is Python 3.7

### ISSUE THREAD

**Issue by rudolphfroger** [bdauvergne/python-oath#33]
When using oath in Python 3.7 with warnings enabled one gets:

    oath/_ocra.py:240: DeprecationWarning: invalid escape sequence \d
    oath/_ocra.py:242: DeprecationWarning: invalid escape sequence \d

This is trivially solved by using raw strings (eg. `r'\d+[HMS]'`).

**Comment by bdauvergne** [comment]
Fixed in c16d64bca34e67e8b2085c67ed45827387028b01

**Comment by rudolphfroger** [comment]
Thanks a lot! I think you just published a py2-only wheel on pypi.org. Could you publish tar.gz (like 1.4.2) or a py2+3 wheel? Thanks!
