### ISSUE TITLE
sha256 and sha512 not working properly

### ISSUE THREAD

**Issue by amascii** [bdauvergne/python-oath#34]
totp/hotp doesn't return the correct key, code used below:

```python import oath
import binascii
import hashlib
x=b'12345678901234567890'
y=binascii.hexlify(x)
r = oath.hotp(y.decode('utf-8'), 1, format='dec8', hash=hashlib.sha256)
q = oath.totp(y.decode('utf-8'), t=59, format='dec8', hash=hashlib.sha256)
print(f'hotp: {r}')
print(f'totp: {q}')
```

According to the test vectors in https://tools.ietf.org/html/rfc6238#appendix-B the result should be `46119246 `, however `32247374` is returned. Using sha1 correctly produces `94287082 `.

**Comment by bdauvergne** [comment]
The test vectors of the RFC are part of the test suite, but there was an errata about the seed values which is false in the published RFC (unfortunately erratas take a long time to be integrated to RFCs), see https://www.rfc-editor.org/errata_search.php?rfc=6238
